language: java
sudo: false
script: mvn clean verify
dist: ShopApp/target

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $ShopApp  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: developer