language: java
sudo: false
script: mvn clean verify

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $ShopApp  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master